annotations:
  group: fun.freechat
cert:
  manager:
    namespace: cert-manager
    version: v1.16.1
ingress:
  annotations:
    cert-manager.io/cluster-issuer: freechat-vllm-letsencrypt-http01
  className: nginx
  enabled: false
  hosts:
    - host: vllm.freechat.fun
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - vllm.freechat.fun
      secretName: freechat-vllm-tls
replicaCount: 1
tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Exists
healthChecks:
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 10
podAnnotations: {}
vllm:
  env:
    - name: CUDA_VISIBLE_DEVICES
      value: "0"
    - name: VLLM_USE_MODELSCOPE
      value: "True"
    - name: VLLM_USE_FLASHINFER_SAMPLER
      value: "0"
